Versao 1/TPRM.MVC/Controllers/EmpresasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using PagedList;
using TPRM.Application.Interface;
using TPRM.Domain.Entities;
using TPRM.MVC.ViewModels;

namespace TPRM.MVC.Controllers
{
    [Authorize(Roles = "admin")]
    public class EmpresasController : Controller
    {

        private readonly IEmpresaAppService _empresaApp;
        private readonly IServicoAppService _servicoApp;

        public EmpresasController(IEmpresaAppService empresaApp, IServicoAppService servicoApp)
        {
            _empresaApp = empresaApp;
            _servicoApp = servicoApp;
        }

        // GET: Empresas
        //public ActionResult Index()
        //{
        //    var empresaViewModel = Mapper.Map<IEnumerable<Empresa>, IEnumerable<EmpresaViewModel>>(_empresaApp.GetAll());
        //    return View(empresaViewModel);
        //}

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var empresaViewModel = Mapper.Map<IEnumerable<Empresa>, IEnumerable<EmpresaViewModel>>(_empresaApp.GetAll());

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NomeParam = string.IsNullOrEmpty(sortOrder) ? "Nome_desc" : "";
            ViewBag.TipoParam = string.IsNullOrEmpty(sortOrder) ? "Tipo_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                empresaViewModel = empresaViewModel.Where(p => p.EmpresaNome.ToUpper().Contains(searchString.ToUpper()) ||
                                                                   p.EmpresaTipo.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "Nome_desc":
                    empresaViewModel = empresaViewModel.OrderByDescending(s => s.EmpresaNome);
                    break;
                case "Tipo_desc":
                    empresaViewModel = empresaViewModel.OrderByDescending(s => s.EmpresaTipo);
                    break;
                default:
                    empresaViewModel = empresaViewModel.OrderBy(p => p.ValorDevido);
                    break;
            }

            int pageSize = 3;
            int pageNumber = page ?? 1;
            return View(empresaViewModel.ToPagedList(pageNumber, pageSize));
        }

        // GET: Empresas/Details/5
        public ActionResult Details(int id)
        {
            var empresa = _empresaApp.GetById(id);
            var empresaViewModel = Mapper.Map<Empresa, EmpresaViewModel>(empresa);

            return View(empresaViewModel);
        }

        // GET: Empresas/Create
        public ActionResult Create()
        {
            ViewBag.EmpresaTipo = new SelectList(new EmpresaViewModel.Tipo().ListaTipos(), "TipoId", "Nome");
            ViewBag.ServicoId = new SelectList(_servicoApp.GetAll(), "ServicoId", "DescricaoServico");
            return View();
        }

        // POST: Empresas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EmpresaViewModel empresa)
        {
            if (ModelState.IsValid)
            {
                var empresaDomain = Mapper.Map<EmpresaViewModel, Empresa>(empresa);
                _empresaApp.Add(empresaDomain);
                return RedirectToAction("Index");
            }

            return View(empresa);
        }

        // GET: Empresas/Edit/5
        public ActionResult Edit(int id)
        {
            var empresa = _empresaApp.GetById(id);
            var empresaViewModel = Mapper.Map<Empresa, EmpresaViewModel>(empresa);

            ViewBag.EmpresaTipo = new SelectList(_empresaApp.GetAll(), "EmpresaTipo", "EmpresaTipo", empresaViewModel.EmpresaTipo);
            ViewBag.EmpresaTipo = new SelectList(new EmpresaViewModel.Tipo().ListaTipos(), "TipoId", "Nome", empresaViewModel.EmpresaTipo);

            ViewBag.ServicoId = new SelectList(_servicoApp.GetAll(), "ServicoId", "DescricaoServico", empresaViewModel.ServicoId);

            return View(empresaViewModel);
        }

        // POST: Empresas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EmpresaViewModel empresa)
        {
            if (ModelState.IsValid)
            {
                var empresaDomain = Mapper.Map<EmpresaViewModel, Empresa>(empresa);
                _empresaApp.Update(empresaDomain);

                return RedirectToAction("Index");
            }

            ViewBag.EmpresaTipo = new SelectList(new EmpresaViewModel.Tipo().ListaTipos(), "TipoId", "Nome");
            ViewBag.ServicoId = new SelectList(_servicoApp.GetAll(), "ServicoId", "DescricaoServico");
            return View(empresa);
        }

        // GET: Empresas/Delete/5
        public ActionResult Delete(int id)
        {
            var empresa = _empresaApp.GetById(id);
            var empresaViewModel = Mapper.Map<Empresa, EmpresaViewModel>(empresa);

            return View(empresaViewModel);
        }

        // POST: Empresas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var empresa = _empresaApp.GetById(id);
            _empresaApp.Remove(empresa);

            return RedirectToAction("Index");
        }
    }
}

Versao 1/TPRM.MVC/Controllers/ServicosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using PagedList;
using TPRM.Application.Interface;
using TPRM.Domain.Entities;
using TPRM.MVC.ViewModels;

namespace TPRM.MVC.Controllers
{
    
    public class ServicosController : Controller
    {

        private readonly IServicoAppService _servicoApp;
        public ServicosController(IServicoAppService servicoApp)
        {
            _servicoApp = servicoApp;
        }

        [Authorize(Roles = "admin, analista")]
        // GET: Servicos
        //public ActionResult Index()
        //{
        //    var servicoViewModel = Mapper.Map<IEnumerable<Servico>, IEnumerable<ServicoViewModel>>(_servicoApp.GetAll());
        //    return View(servicoViewModel);
        //}
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var servicoViewModel = Mapper.Map<IEnumerable<Servico>, IEnumerable<ServicoViewModel>>(_servicoApp.GetAll());
            ViewBag.CurrentSort = sortOrder;
            ViewBag.DescricaoParam = string.IsNullOrEmpty(sortOrder) ? "Descricao_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                servicoViewModel = servicoViewModel.Where(p => p.DescricaoServico.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "Descricao_desc":
                    servicoViewModel = servicoViewModel.OrderByDescending(s => s.DescricaoServico);
                    break;
                default:
                    servicoViewModel = servicoViewModel.OrderBy(p => p.DataCadastro);
                    break;
            }

            int pageSize = 3;
            int pageNumber = page ?? 1;
            return View(servicoViewModel.ToPagedList(pageNumber, pageSize));
        }

        [Authorize(Roles = "admin")]
        // GET: Servicos/Details/5
        public ActionResult Details(int id)
        {
            var servico = _servicoApp.GetById(id);
            var servicoViewModel = Mapper.Map<Servico, ServicoViewModel>(servico);

            return View(servicoViewModel);
        }

        [Authorize(Roles = "admin")]
        // GET: Servicos/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        // POST: Servicos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ServicoViewModel servico)
        {
            if (ModelState.IsValid)
            {
                var servicoDomain = Mapper.Map<ServicoViewModel, Servico>(servico);
                _servicoApp.Add(servicoDomain);
                return RedirectToAction("Index");
            }

            return View(servico);
        }

        [Authorize(Roles = "admin")]
        // GET: Servicos/Edit/5
        public ActionResult Edit(int id)
        {
            var servico = _servicoApp.GetById(id);
            var servicoViewModel = Mapper.Map<Servico, ServicoViewModel>(servico);

            return View(servicoViewModel);
        }

        [Authorize(Roles = "admin")]
        // POST: Servicos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ServicoViewModel servico)
        {
            if (ModelState.IsValid)
            {
                var servicoDomain = Mapper.Map<ServicoViewModel, Servico>(servico);
                _servicoApp.Update(servicoDomain);

                return RedirectToAction("Index");
            }

            return View(servico);
        }

        //// GET: Servicos/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    var servico = _servicoApp.GetById(id);
        //    var servicoViewModel = Mapper.Map<Servico, ServicoViewModel>(servico);

        //    return View(servicoViewModel);
        //}

        //// POST: Servicos/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    var servico = _servicoApp.GetById(id);
        //    _servicoApp.Remove(servico);

        //    return RedirectToAction("Index");
        //}
    }
}

Versao 1/TPRM.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <section class="jk-header">
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"><img src="~/Imagem/Bernhoeft02.png" /></a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        @if (Request.IsAuthenticated)
                        {
                            if (User.IsInRole("admin"))
                            {
                                <li>@Html.ActionLink("SERVIÇOS", "Index", "Servicos")</li>
                                <li>@Html.ActionLink("EMPRESAS", "Index", "Empresas")</li>
                                <li>@Html.ActionLink("TRANSAÇÕES", "Index", "Transacoes")</li>
                            }
                            else if (User.IsInRole("analista"))
                            {
                                <li>@Html.ActionLink("SERVIÇOS", "Index", "Servicos")</li>
                                <li>@Html.ActionLink("TRANSAÇÕES", "Index", "Transacoes")</li>
                            }
                            else if (User.IsInRole("cliente"))
                            {
                                <li>@Html.ActionLink("TRANSAÇÕES", "Index", "Transacoes")</li>
                            }

                        }
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="active">@Html.Partial("_LoginPartial")</li>
                    </ul>
                </div>
            </div>
        </nav>
    </section>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sistema TPRM - Todos os direitos reservados</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>