Versao 1/TPRM.MVC/Controllers/TransacoesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using PagedList;
using TPRM.Application.Interface;
using TPRM.Domain.Entities;
using TPRM.MVC.ViewModels;

namespace TPRM.MVC.Controllers
{
    public class TransacoesController : Controller
    {
        private readonly ITransacaoAppService _transacaoApp;
        private readonly IEmpresaAppService _empresaApp;
        private readonly IServicoAppService _servicoApp;

        public TransacoesController(IEmpresaAppService empresaApp, IServicoAppService servicoApp, ITransacaoAppService transacaoApp)
        {
            _empresaApp = empresaApp;
            _servicoApp = servicoApp;
            _transacaoApp = transacaoApp;
        }

        [Authorize(Roles = "cliente, admin, analista")]
        // GET: Transacao
        //public ActionResult Index()
        //{
        //    var transacaoViewModel = Mapper.Map<IEnumerable<Transacao>, IEnumerable<TransacaoViewModel>>(_transacaoApp.GetAll());
        //    return View(transacaoViewModel);
        //}

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var transacaoViewModel = Mapper.Map<IEnumerable<Transacao>, IEnumerable<TransacaoViewModel>>(_transacaoApp.GetAll());

            ViewBag.CurrentSort = sortOrder;
            ViewBag.EmpresaContratadaParam = string.IsNullOrEmpty(sortOrder) ? "EmpresaContratada_desc" : "";
            ViewBag.EmpresaContratanteParam = string.IsNullOrEmpty(sortOrder) ? "EmpresaContratante_desc" : "";
            ViewBag.StatusParam = string.IsNullOrEmpty(sortOrder) ? "Status_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                transacaoViewModel = transacaoViewModel.Where(p => p.NomeEmpresaContratada.ToUpper().Contains(searchString.ToUpper()) ||
                                             p.NomeEmpresaContratante.ToUpper().Contains(searchString.ToUpper()) ||
                                             p.Status.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "EmpresaContratada_desc":
                    transacaoViewModel = transacaoViewModel.OrderByDescending(s => s.NomeEmpresaContratada);
                    break;
                case "EmpresaContratante_desc":
                    transacaoViewModel = transacaoViewModel.OrderByDescending(s => s.NomeEmpresaContratante);
                    break;
                case "Status_desc":
                    transacaoViewModel = transacaoViewModel.OrderByDescending(s => s.Status);
                    break;
                default:
                    transacaoViewModel = transacaoViewModel.OrderBy(p => p.DataCadastro);
                    break;
            }

            int pageSize = 3;
            int pageNumber = page ?? 1;
            return View(transacaoViewModel.ToPagedList(pageNumber, pageSize));
        }

        [Authorize(Roles = "cliente, admin, analista")]
        // GET: Transacao/Details/5
        public ActionResult Details(int id)
        {
            var transacao = _transacaoApp.GetById(id);
            var transacaoViewModel = Mapper.Map<Transacao, TransacaoViewModel>(transacao);

            return View(transacaoViewModel);
        }
        
        [Authorize(Roles = "cliente, admin")]
        // GET: Transacao/Create
        public ActionResult Create()
        {
            ViewBag.Status = new SelectList(new TransacaoViewModel.StatusTipo().ListaStatus(), "StatusId", "Nome");
            ViewBag.ServicoId = new SelectList(_servicoApp.GetAll(), "ServicoId", "DescricaoServico");
            ViewBag.EmpresaContratanteId = new SelectList(_empresaApp.GetAll().Where(p => p.EmpresaTipo == "Contratante"), "EmpresaId", "EmpresaNome");
            ViewBag.EmpresaContratadaId = new SelectList(_empresaApp.GetAll().Where(p => p.EmpresaTipo == "Contratado"), "EmpresaId", "EmpresaNome");
            return View();
        }

        [Authorize(Roles = "cliente, admin")]
        // POST: Transacao/Create
        [HttpPost]
        public ActionResult Create(TransacaoViewModel transacao)
        {
            if (ModelState.IsValid)
            {
                if (transacao.Files != null)
                {
                    HttpPostedFileBase files = transacao.Files;

                    var transacaoDomain = Mapper.Map<TransacaoViewModel, Transacao>(transacao);

                    var extension = Path.GetExtension(files.FileName);
                    if (extension != null)
                    {
                        String fileExt = extension.ToUpper();

                        if (fileExt == ".PDF")
                        {
                            Stream str = files.InputStream;
                            BinaryReader br = new BinaryReader(str);
                            Byte[] fileDet = br.ReadBytes((Int32) str.Length);

                            transacaoDomain.FileName = files.FileName;
                            transacaoDomain.File = fileDet;
                            transacaoDomain.NomeEmpresaContratada = _empresaApp.GetById(transacao.EmpresaContratadaId).EmpresaNome;
                            transacaoDomain.NomeEmpresaContratante = _empresaApp.GetById(transacao.EmpresaContratanteId).EmpresaNome;
                            _transacaoApp.Add(transacaoDomain);

                            var empresaDomain = _empresaApp.GetById(transacaoDomain.EmpresaContratanteId);
                            empresaDomain.ValorDevido = empresaDomain.ValorDevido + 5;
                            _empresaApp.Update(empresaDomain);

                            return RedirectToAction("Index");
                        }
                        else
                        {
                            ViewBag.FileStatus = "Formato de arquivo inválido";
                        }
                    }
                }
                else
                {
                    ViewBag.FileStatus = "Escolha um arquivo pdf";
                }
            }

            ViewBag.ServicoId = new SelectList(_servicoApp.GetAll(), "ServicoId", "DescricaoServico");
            ViewBag.EmpresaContratanteId = new SelectList(_empresaApp.GetAll().Where(p => p.EmpresaTipo == "Contratante"), "EmpresaId", "EmpresaNome");
            ViewBag.EmpresaContratadaId = new SelectList(_empresaApp.GetAll().Where(p => p.EmpresaTipo == "Contratado"), "EmpresaId", "EmpresaNome");

            return View(transacao);
        }

        [Authorize(Roles = "analista, admin")]
        // GET: Transacao/Edit/5
        public ActionResult Edit(int id)
        {
            var transacao = _transacaoApp.GetById(id);
            var transacaoViewModel = Mapper.Map<Transacao, TransacaoViewModel>(transacao);

            ViewBag.Status = new SelectList(new TransacaoViewModel.StatusTipo().ListaStatus(), "StatusId", "Nome", transacaoViewModel.Status);
            ViewBag.ServicoId = new SelectList(_servicoApp.GetAll(), "ServicoId", "DescricaoServico", transacaoViewModel.ServicoId);
            //ViewBag.EmpresaId = new SelectList(_empresaApp.GetAll(), "EmpresaId", "EmpresaNome", transacaoViewModel.EmpresaId);

            return View(transacaoViewModel);
        }

        [Authorize(Roles = "analista, admin")]
        // POST: Transacao/Edit/5
        [HttpPost]
        public ActionResult Edit(TransacaoViewModel transacao)
        {
            if (ModelState.IsValid)
            {
                var transacaoDomain = Mapper.Map<TransacaoViewModel, Transacao>(transacao);
                _transacaoApp.Update(transacaoDomain);

                return RedirectToAction("Index");
            }

            ViewBag.Status = new SelectList(new TransacaoViewModel.StatusTipo().ListaStatus(), "StatusId", "Nome", transacao.Status);
            ViewBag.ServicoId = new SelectList(_servicoApp.GetAll(), "ServicoId", "DescricaoServico", transacao.ServicoId);
            //ViewBag.EmpresaId = new SelectList(_empresaApp.GetAll(), "EmpresaId", "EmpresaNome", transacao.EmpresaId);

            return View(transacao);
        }

        [Authorize(Roles = "admin")]
        // GET: Transacao/Delete/5
        public ActionResult Delete(int id)
        {
            var transacao = _transacaoApp.GetById(id);
            var transacaoViewModel = Mapper.Map<Transacao, TransacaoViewModel>(transacao);

            return View(transacaoViewModel);
        }

        [Authorize(Roles = "admin")]
        // POST: Transacao/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var transacao = _transacaoApp.GetById(id);
            _transacaoApp.Remove(transacao);

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "analista, admin")]
        public ActionResult Download(int id)
        {
            var pdf = _transacaoApp.GetById(id); //_pdfUploadContext.FilesContainer.FirstOrDefault(p => p.Id == id);
            return File(pdf.File, "application/pdf", pdf.FileName);
        }
    }
}

Versao 1/TPRM.MVC/Views/Transacoes/Create.cshtml
@model TPRM.MVC.ViewModels.TransacaoViewModel

@{
    ViewBag.Title = "Create";
}

<h2 class="titulo">Criar uma transação</h2>

@using (Html.BeginForm("Create", "Transacoes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.ServicoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ServicoId", String.Empty)
                @Html.ValidationMessageFor(model => model.ServicoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmpresaContratanteId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmpresaContratanteId", String.Empty)
                @Html.ValidationMessageFor(model => model.EmpresaContratanteId, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.EmpresaContratadaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmpresaContratadaId", String.Empty)
                @Html.ValidationMessageFor(model => model.EmpresaContratadaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Files, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Files, "", new { @type = "file", @multiple = "multiple" })
                @Html.ValidationMessageFor(model => model.Files, "", new { @class = "text-danger" })
            </div>
        </div> 
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 text-success">
                @ViewBag.FileStatus
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar a lista", "Index")
</div>

Versao 1/TPRM.MVC/Views/Transacoes/Delete.cshtml
@model TPRM.MVC.ViewModels.TransacaoViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TransacaoViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ServicoId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServicoId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmpresaContratanteId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpresaContratanteId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmpresaContratadaId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpresaContratadaId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Motivo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Motivo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Versao 1/TPRM.MVC/Views/Transacoes/Details.cshtml
@model TPRM.MVC.ViewModels.TransacaoViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TransacaoViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ServicoId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Servico.DescricaoServico)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmpresaId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empresa.EmpresaNome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Motivo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Motivo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TransacaoId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Versao 1/TPRM.MVC/Views/Transacoes/Edit.cshtml
@using TPRM.MVC.ViewModels
@model TPRM.MVC.ViewModels.TransacaoViewModel

@{
    ViewBag.Title = "Edit";
}

<h2 class="titulo">Editar a transacao</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TransacaoId)

        @Html.HiddenFor(model => model.ServicoId, new { htmlAttributes = new { @class = "form-control" } })
        @Html.HiddenFor(model => model.EmpresaContratanteId, new { htmlAttributes = new { @class = "form-control" } })
        @Html.HiddenFor(model => model.NomeEmpresaContratante, new { htmlAttributes = new { @class = "form-control" } })
        @Html.HiddenFor(model => model.EmpresaContratadaId, new { htmlAttributes = new { @class = "form-control" } })
        @Html.HiddenFor(model => model.NomeEmpresaContratada, new { htmlAttributes = new { @class = "form-control" } })
        @Html.HiddenFor(model => model.FileName, new { htmlAttributes = new { @class = "form-control" } })

        <div class="form-group">
            @Html.LabelFor(model => model.Motivo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Motivo, new { htmlAttributes = new { @class = "form-control disabled" } })
                @Html.ValidationMessageFor(model => model.Motivo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Status", String.Empty)
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar a lista", "Index")
</div>

Versao 1/TPRM.MVC/Views/Transacoes/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<TPRM.MVC.ViewModels.TransacaoViewModel>

@{
    ViewBag.Title = "Index";
}

<h2 class="titulo">Lista de Transações</h2>

<div class="row">
    <div class="col-md-6">
        @if (User.IsInRole("admin") || User.IsInRole("cliente"))
        {
            @Html.ActionLink("Criar Novo", "Create", 1, new { @class = "btn btn-success" })
        }
    </div>
    <div class="col-md-4">
        @using (Html.BeginForm("Index", "Transacoes", FormMethod.Get))
        {
            <div class="input-group">
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="submit">Pesquisar</button>
                </span>
                @Html.TextBox("searchString", null, new { @class = "form-control", @placeholder = "Nome da empresa ou status..." })

            </div>
        }

    </div>
</div>
<br />

<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayName("Serviço")
        </th>
        <th>
            @Html.ActionLink("Contratada", "Index", new { sortOrder = ViewBag.EmpresaContratadaParam })
        </th>
        <th>
            @Html.ActionLink("Contratante", "Index", new { sortOrder = ViewBag.EmpresaContratanteParam })
        </th>
        <th>
            @Html.DisplayName("Motivo")
        </th>
        <th>
            @Html.ActionLink("Status", "Index", new { sortOrder = ViewBag.StatusParam })
        </th>
        <th>
            @Html.DisplayName("Arquivo")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Servico.DescricaoServico)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NomeEmpresaContratada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NomeEmpresaContratante)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Motivo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FileName)
            </td>
            <td>
                @if (User.IsInRole("admin") || User.IsInRole("analista"))
                {
                    @Html.ActionLink("Editar", "Edit", new { id = item.TransacaoId }, new { @class = "btn btn-primary btn-be" })

                }
            </td>
            <td>
                @if (User.IsInRole("admin") || User.IsInRole("analista"))
                {
                    @Html.ActionLink("Download", "Download", new { id = item.TransacaoId }, new { @class = "btn btn-primary btn-be" })
                }
            </td>
        </tr>
    }

</table>

Pagina @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))